name: publish

on:
  push:
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every night

permissions:
  contents: write # for creating a release
  packages: write # for publishing containers
  id-token: write # for using OIDC tokens

env:
  SYFT_VERSION: "0.68.1"
  IMAGE_NAME: swio

jobs:

  # check that our CI would pass
  ci:
    uses: ./.github/workflows/ci.yaml

  container:
      needs: [ ci ]

      uses: ./.github/workflows/containers.yaml
      secrets: inherit

      with:
        imageTag: "latest"
        platforms: "linux/amd64"

  publish:
    permissions:
      contents: read
      packages: write

    needs: [ ci, container ]
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/download-artifact@v3
          with:
            path: ~/download
        - name: Display downloaded content
          run: ls -R ~/download
        - name: Load container
          run: |
              podman load --input ~/download/container/image.tar

        - name: Log in to ghcr.io
          uses: redhat-actions/podman-login@v1
          with:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: "ghcr.io"

        - name: Push to ghcr.io
          id: push-images
          env:
            IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
          run: |
            podman push \
              "${{ env.IMAGE_NAME }}:latest" \
              "${IMAGE}" \
              --digestfile "${RUNNER_TEMP}/push.digest"
            echo "imageDigest=$(cat ${RUNNER_TEMP}/push.digest)" >> $GITHUB_OUTPUT
              rm ${RUNNER_TEMP}/push.digest